var BATTLES = [
    {
        "title": "First Battle of St. Albans",
        "type": "Battle",
        "yorkactors": "Richard Duke of York, Richard Neville Earl of Salisbury, Richard Neville Earl of Warwick", 
        "lancasteractors": "Henry VI, Edmund Beaufort, Humphrey Stafford, Henry Percy, Thomas Courtenay, Thomas Baron Clifford",
        "day": 22,
        "month": "May",
        "year": 1455,
        "latitude": 51.7467822,
        "longitude": 0.373782,
        "description": "Decisive Yorkist Victory, Richard of York named Lord Protector",
        "victor": 1,
    },
    {
        "title": "Battle of Blore Heath",
        "type": "Battle",
        "yorkactors": "Richard Neville Earl of Salisbury, Sir John Neville, Thomas Neville",
        "lancasteractors": "James Tuchet Lord Audley, John Sutton Lord Dudley", 
        "day": 23,
        "month": "September",
        "year": 1459,
        "latitude": 52.9086591,
        "longitude": -2.4268678,
        "description": "Yorkist Victory",
        "victor": 1,
    },
    {
        "title": "Battle of Ludford Bridge",
        "type": "Battle",
        "yorkactors": "Richard Duke of York, Richard Neville Earl of Salisbury, Richard Neville Earl of Warwick", 
        "lancasteractors": "Henry VI, Humphrey Stafford",
        "day": 12,
        "month": "October",
        "year": 1459,
        "latitude": 52.361,
        "longitude": 2.718,
        "description": "Lancastrian Victory",
        "victor": 0,
    },
 
];